<?php /** @var Mage_Adminhtml_Block_Template $this */ // @codingStandardsIgnoreFile ?>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td>
                <h3>e2MPro is currently under maintenance</h3>
            </td>
        </tr>
    </table>
</div>

<p>The Module interface is unavailable and the background tasks stop running. Service can be put under maintenance
    automatically due to the following reasons:</p>

<ul style="margin-left: 30px;">
    <li style="list-style-type: disc">
        <p>Module installation failed, e.g. due to the incorrect installation via Magento Component Manager,
            incompatibility of Magento and its Modules or other related technical issues.</p>
    </li>
    <li style="list-style-type: disc">
        <p>Module upgrade failed, e.g. due to the improper M2E Pro tables updating.</p>
    </li>
</ul>

<p>Please contact <a href="mailto:support@m2epro.com" title="support@m2epro.com">M2E Pro Support Team</a> to
    resolve the issue.</p>
