<?php /** @var M2E_e2M_Block_Adminhtml_Main $this */ ?>

<script type="text/javascript">

    var e2m = {};

    //----------------------------------------

    e2m.url = {};
    e2m.localStorage = {};
    e2m.prefix = 'm2e_e2m';

    //----------------------------------------

    e2m.url.skin = '<?php echo $this->getSkinUrl('e2m') ?>';
    e2m.url.cron = '<?php echo $this->getUrl('*/e2m/cron') ?>';
    e2m.url.getBeforeEbayToken = '<?php echo $this->getUrl('*/e2m/getBeforeEbayToken') ?>';
    e2m.url.unsetEbayToken = '<?php echo $this->getUrl('*/e2m/unsetEbayToken') ?>';
    e2m.url.setSettings = '<?php echo $this->getUrl('*/e2m/setSettings') ?>';
    e2m.url.getAttributesBySetId = '<?php echo $this->getUrl('*/e2m/getAttributesBySetId') ?>';
    e2m.url.startTaskDownloadInventory = '<?php echo $this->getUrl('*/e2m/startTaskDownloadInventory') ?>';
    e2m.url.startTaskImportInventory = '<?php echo $this->getUrl('*/e2m/startTaskImportInventory') ?>';
    e2m.url.pauseStartTaskImportInventory = '<?php echo $this->getUrl('*/e2m/pauseStartTaskImportInventory') ?>';
    e2m.url.pauseFinishTaskImportInventory = '<?php echo $this->getUrl('*/e2m/pauseFinishTaskImportInventory') ?>';

    //----------------------------------------

    e2m.magentoAttributes = JSON.parse('<?php echo str_replace("'", '', $this->getCoreHelper()->jsonEncode($this->getDataHelper()->getMagentoAttributes($this->getConfigHelper()->getAttributeSet()))) ?>');
    e2m.eBayFields = JSON.parse('<?php echo $this->getCoreHelper()->jsonEncode($this->getInventoryHelper()->getEbayFields()) ?>');

    e2m.attributes = JSON.parse('<?php if (empty($this->getConfigHelper()->getEbayFieldMagentoAttribute())) { echo '{}'; } else { echo str_replace("'", '', $this->getCoreHelper()->jsonEncode($this->getConfigHelper()->getEbayFieldMagentoAttribute())); } ?>');
</script>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td>
                <h3><?php echo $this->getDataHelper()->__('eBay Data Import'); ?></h3>
                <?php if (!empty($this->getAccountHelper()->getUserId())): ?>
                    <div style="float: right">
                        <label><?php echo $this->getDataHelper()->__('eBay User ID'); ?>&nbsp;</label>
                        <span>(<a target="_blank" href="<?php echo $this->getAccountHelper()->getAccountUrl(); ?>"><?php echo $this->escapeHtml($this->getAccountHelper()->getUserId()); ?></a>)</span>
                        <span><?php echo $this->getChildHtml('logout_button'); ?></span>
                    </div>
                <?php endif; ?>
            </td>
        </tr>
    </table>
</div>

<?php if (empty($this->getAccountHelper()->getToken())): ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo $this->getDataHelper()->__('Get Access'); ?></h4>
        </div>
        <div class="fieldset">
            <div>
                <table class="form-list" cellspacing="0" cellpadding="0">
                    <tr>
                        <td class="label">
                            <label for="account-mode"><?php echo $this->getDataHelper()->__('Environment'); ?>:<span
                                        class="required">*</span></label>
                        </td>
                        <td class="value" style="width: auto">
                            <select id="account-mode">
                                <option value="<?php echo M2E_e2M_Helper_eBay_Account::MODE_SANDBOX; ?>" <?php if ($this->getAccountHelper()->getMode() === M2E_e2M_Helper_eBay_Account::MODE_SANDBOX): echo ' selected="selected"'; endif; ?>><?php echo $this->getDataHelper()->__('Sandbox (Test)'); ?></option>
                                <option value="<?php echo M2E_e2M_Helper_eBay_Account::MODE_PRODUCTION; ?>" <?php if ($this->getAccountHelper()->getMode() === M2E_e2M_Helper_eBay_Account::MODE_PRODUCTION): echo ' selected="selected"'; endif; ?>><?php echo $this->getDataHelper()->__('Production (Live)'); ?></option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label><?php echo $this->getDataHelper()->__('Grant Access'); ?>:</label>
                        </td>
                        <td class="value" style="width: auto">
                            <?php echo $this->getChildHtml('get_token_button'); ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if (!empty($this->getAccountHelper()->getToken())): ?>
    <div class="entry-edit">
        <header class="entry-edit-head">
            <h4><?php echo $this->getDataHelper()->__('Summary inventory'); ?></h4>
        </header>
        <div class="fieldset">
            <div>
                <table class="form-list" cellspacing="0" cellpadding="0">
                    <tr>
                        <td class="label">
                            <label><?php echo $this->getDataHelper()->__('Total items downloaded'); ?>:</label>
                        </td>
                        <td class="value" style="width: auto">
                            <span id="download-inventory-total-items"><?php echo $this->escapeHtml($this->getInventoryHelper()->getItemsTotal()) ?></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label><?php echo $this->getDataHelper()->__('Variation items'); ?>:</label>
                        </td>
                        <td class="value" style="width: auto">
                            <span id="download-inventory-variation-items"><?php echo $this->escapeHtml($this->getInventoryHelper()->getItemsVariation()); ?></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label><?php echo $this->getDataHelper()->__('Simple items'); ?>:</label>
                        </td>
                        <td class="value" style="width: auto">
                            <span id="download-inventory-simple-items"><?php echo $this->escapeHtml($this->getInventoryHelper()->getItemsSimple()); ?></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <?php echo $this->getChildHtml('start_download_inventory_button'); ?>
                        </td>
                        <td class="value block-download-inventory-progress" style="width: auto">
                            <span id="download-inventory-progress"><?php echo $this->escapeHtml($this->getProgressHelper()->getProgressByTag(M2E_e2M_Model_Cron_Task_eBay_DownloadInventory::TAG)); ?></span>%
                        </td>
                    </tr>
                    <?php if ($this->getProgressHelper()->isCompletedProgressByTag(M2E_e2M_Model_Cron_Task_eBay_DownloadInventory::TAG)): ?>
                        <tr>
                            <td class="label">
                                <?php echo $this->getChildHtml('start_import_inventory_button'); ?>
                            </td>
                            <td class="value" style="width: auto">
                                <span id="import-inventory-progress"><?php echo $this->escapeHtml($this->getProgressHelper()->getProgressByTag(M2E_e2M_Model_Cron_Task_Magento_ImportInventory::TAG)); ?></span>%
                            </td>
                        </tr>
                        <tr>
                            <td id="pause-download-inventory-button" class="label">
                                <?php echo $this->getChildHtml('pause_download_inventory_button'); ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                </table>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if ($this->getProgressHelper()->isCompletedProgressByTag(M2E_e2M_Model_Cron_Task_eBay_DownloadInventory::TAG)): ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo $this->getDataHelper()->__('Marketplace settings'); ?></h4>
        </div>
        <div class="fieldset">
            <table class="form-list" cellspacing="0" cellpadding="0">
                <?php foreach ($this->getInventoryHelper()->getMarketplaces() as $marketplaceId): ?>
                    <tr>
                        <td class="label">
                            <label for="<?php echo $marketplaceId; ?>"><?php echo $this->getDataHelper()->__($this->getInventoryHelper()->getMarketplaceTitle($marketplaceId)); ?></label>
                        </td>
                        <td class="value" style="width: auto">
                            <select id="<?php echo $marketplaceId; ?>" class="marketplace-store config-input">
                                <option value="">-- Please Select --</option>
                                <option value="<?php echo M2E_e2M_Helper_eBay_Config::SKIP ?>" <?php if ($this->getConfigHelper()->isSkipStore($marketplaceId)) echo ' selected="selected"'; ?>>Skip</option>
                                <?php foreach ($this->getDataHelper()->getMagentoStores() as $id => $store): ?>
                                    <option value="<?php echo $id; ?>" <?php if ($this->getConfigHelper()->getStoreForMarketplace($marketplaceId) === $id) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__($store); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
<?php endif; ?>

<?php if ($this->getProgressHelper()->isCompletedProgressByTag(M2E_e2M_Model_Cron_Task_eBay_DownloadInventory::TAG)): ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo $this->getDataHelper()->__('Inventory settings'); ?></h4>
        </div>
        <div class="fieldset">
            <table class="form-list" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="label">
                        <label for="inventory-settings-product-identifier"><?php echo $this->getDataHelper()->__('Product ID'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto">
                        <select id="inventory-settings-product-identifier" class="config-input">
                            <option value="<?php echo M2E_e2M_Helper_eBay_Config::VALUE_SKU_PRODUCT_IDENTIFIER; ?>" <?php if ($this->getConfigHelper()->isProductIdentifierSKU()) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__('SKU'); ?></option>
                            <option value="<?php echo M2E_e2M_Helper_eBay_Config::VALUE_MPN_PRODUCT_IDENTIFIER; ?>" <?php if ($this->getConfigHelper()->isProductIdentifierMPN()) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__('MPN'); ?></option>
                            <option value="<?php echo M2E_e2M_Helper_eBay_Config::VALUE_UPC_PRODUCT_IDENTIFIER; ?>" <?php if ($this->getConfigHelper()->isProductIdentifierUPC()) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__('UPC'); ?></option>
                            <option value="<?php echo M2E_e2M_Helper_eBay_Config::VALUE_EAN_PRODUCT_IDENTIFIER; ?>" <?php if ($this->getConfigHelper()->isProductIdentifierEAN()) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__('EAN'); ?></option>
                            <option value="<?php echo M2E_e2M_Helper_eBay_Config::VALUE_GTIN_PRODUCT_IDENTIFIER; ?>" <?php if ($this->getConfigHelper()->isProductIdentifierGTIN()) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__('GTIN'); ?></option>
                        </select>
                        <p class="note">
                                <span><?php echo Mage::helper('e2m')->__('Product identifier on different marketplaces'); ?>
                                </span>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="inventory-settings-action-found"><?php echo $this->getDataHelper()->__('Found a product'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto">
                        <select id="inventory-settings-action-found" class="config-input">
                            <option value="<?php echo M2E_e2M_Helper_eBay_Config::VALUE_IGNORE_ACTION_FOUND; ?>" <?php if (M2E_e2M_Helper_eBay_Config::VALUE_IGNORE_ACTION_FOUND === $this->getConfigHelper()->getActionFound()) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__('Ignore'); ?></option>
                            <option value="<?php echo M2E_e2M_Helper_eBay_Config::VALUE_UPDATE_ACTION_FOUND; ?>" <?php if (M2E_e2M_Helper_eBay_Config::VALUE_UPDATE_ACTION_FOUND === $this->getConfigHelper()->getActionFound()) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__('Update'); ?></option>
                        </select>
                        <p class="note">
                                <span><?php echo Mage::helper('e2m')->__('Action found a product in Magento inventory'); ?>
                                </span>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="import-qty"><?php echo $this->getDataHelper()->__('Create Stock item') ?>:</label>
                    </td>
                    <td class="value" style="width: auto">
                        <select id="import-qty" class="config-input">
                            <option value="1" <?php if ($this->getConfigHelper()->isImportQty() === true) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__('Yes'); ?></option>
                            <option value="0" <?php if ($this->getConfigHelper()->isImportQty() === false) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__('No'); ?></option>
                        </select>
                        <p class="note">
                                <span><?php echo Mage::helper('e2m')->__('Create Stock item (Import QTY)'); ?>
                                </span>
                        </p>
                    </td>
                </tr>
            </table>
        </div>
    </div>
<?php endif; ?>

<?php if ($this->getProgressHelper()->isCompletedProgressByTag(M2E_e2M_Model_Cron_Task_eBay_DownloadInventory::TAG)): ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo $this->getDataHelper()->__('Product settings'); ?></h4>
        </div>
        <div class="fieldset">
            <table class="form-list" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="label">
                        <label for="generate-sku"><?php echo $this->getDataHelper()->__('Generate SKU') ?>:</label>
                    </td>
                    <td class="value">
                        <select id="generate-sku" class="config-input">
                            <option value="1" <?php if ($this->getConfigHelper()->isGenerateSku() === true) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__('Yes'); ?></option>
                            <option value="0" <?php if ($this->getConfigHelper()->isGenerateSku() === false) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__('No'); ?></option>
                        </select>
                        <p class="note">
                                <span><?php echo Mage::helper('e2m')->__('Generate SKU (if empty)'); ?>
                                </span>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="import-image"><?php echo $this->getDataHelper()->__('Import image') ?>:</label>
                    </td>
                    <td class="value" style="width: auto">
                        <select id="import-image" class="config-input">
                            <option value="1" <?php if ($this->getConfigHelper()->isImportImage() === true) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__('Yes'); ?></option>
                            <option value="0" <?php if ($this->getConfigHelper()->isImportImage() === false) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__('No'); ?></option>
                        </select>
                        <p class="note">
                                <span><?php echo Mage::helper('e2m')->__('Import image'); ?>
                                </span>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="delete-html"><?php echo $this->getDataHelper()->__('Delete HTML') ?>:</label>
                    </td>
                    <td class="value" style="width: auto">
                        <select id="delete-html" class="config-input">
                            <option value="1" <?php if ($this->getConfigHelper()->isDeleteHtml() === true) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__('Yes'); ?></option>
                            <option value="0" <?php if ($this->getConfigHelper()->isDeleteHtml() === false) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__('No'); ?></option>
                        </select>
                        <p class="note">
                                <span><?php echo Mage::helper('e2m')->__('Clean HTML in Description'); ?>
                                </span>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="attribute-set"><?php echo $this->getDataHelper()->__('Attribute Set') ?>:</label>
                    </td>
                    <td class="value" style="width: auto">
                        <select id="attribute-set" class="attribute-set config-input">
                            <option value="">-- Please Select --</option>
                            <?php foreach ($this->getDataHelper()->getAllAttributeSet() as $id => $title): ?>
                                <option value="<?php echo $id; ?>" <?php if ($this->getConfigHelper()->getAttributeSet() == $id) echo ' selected="selected"'; ?>><?php echo $this->getDataHelper()->__($title); ?></option>
                            <?php endforeach; ?>
                        </select>
                        <p class="note">
                                <span><?php echo Mage::helper('e2m')->__('Attribute Set'); ?>
                                </span>
                        </p>
                    </td>
                </tr>


                <tr>
                    <td class="label">
                        <label for="ebay-field"><?php echo $this->getDataHelper()->__('eBay fields'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto">
                        <select id="ebay-field" class="ebay-field-magento-attribute config-input">
                            <option value=""></option>
                            <?php foreach ($this->getInventoryHelper()->getEbayFields() as $code => $title): ?>
                                <option value="<?php echo $code; ?>"><?php echo $this->getDataHelper()->__($title); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="magento-attribute"><?php echo $this->getDataHelper()->__('Magento attributes'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto">
                        <select id="magento-attribute" class="ebay-field-magento-attribute config-input">
                            <option value=""></option>
                            <?php foreach ($this->getDataHelper()->getMagentoAttributes($this->getConfigHelper()->getAttributeSet()) as $code => $title): ?>
                                <option value="<?php echo $code; ?>"><?php echo $this->getDataHelper()->__($title); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->getDataHelper()->__('Import properties'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto">

                        <table class="form-list" cellspacing="0" cellpadding="0">
                            <tr>
                                <td class="value" style="width: auto">
                                    <label for="ebay-field"><?php echo $this->getDataHelper()->__('eBay fields'); ?></label>
                                </td>
                                <td class="label">
                                    <label for="magento-attribute">/&nbsp;&nbsp;<?php echo $this->getDataHelper()->__('Magento attributes'); ?></label>
                                </td>
                            </tr>


                            <tr>
                                <td class="value" style="width: auto">
                                    <div id="field-attribute-list-e"></div>
                                </td>
                                <td class="label">
                                    <div id="field-attribute-list-m"></div>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    </div>
<?php endif; ?>

<div <?php if (!$this->getProgressHelper()->isCompletedProgressByTag(M2E_e2M_Model_Cron_Task_eBay_DownloadInventory::TAG) || $this->getConfigHelper()->isFull()): ?> style="display: none" <?php endif; ?> class="config-button">
    <?php echo $this->getChildHtml('send_settings_button'); ?>
</div>
